name: vectorian-demo
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8
  - bokeh>=2.3.1
  - ipywidgets
  - pip
  - pip:
      - vectorian>=0.8.0.dev7
      - sentence-transformers>=0.4
      - jupyter_bokeh>=3.0.0
      - opentsne>=0.6.0
