name: vectorian-notebook
channels:
  - default
  - conda-forge
  - pyviz
dependencies:
  - python=3.9
  - xtl==0.7.2
  - xtensor==0.23.4
  - xsimd==7.4.9
  - xtensor-python==0.25.1
  - bokeh==2.4.0
  - ipywidgets==7.6.3
  - widgetsnbextension==3.5.1
  - beautifulsoup4==4.10
  - scikit-learn==0.24.2
  - matplotlib==3.4.3
  - skl2onnx==1.9.2
  - onnxruntime==1.7.2
  - h5py==2.10.0
  - pyyaml==5.4.1
  - tokenizers==0.10.3
  - sentence-transformers==2.0.0
  - sentencepiece==0.1.95
  - networkx==2.6.2
  - pygraphviz==1.7
  - faiss=1.7.0
  - pip
  - pip:
      - vectorian==0.9.15
      - pybind11==2.6.2
      - gensim>=3.8.3, <4.0.0
      - jupyter_bokeh==3.0.2
      - opentsne==0.6.0
      - spacy==3.1.2
      - spacy_sentence_bert==0.1.2
      - markdown==3.3.4
      - jp_proxy_widget==1.0.10
      - pydot==1.4.2
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0-py3-none-any.whl
