name: vectorian-demo
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8
  - bokeh>=2.3.1
  - ipywidgets
  - widgetsnbextension
  - faiss
  - pip
  - pip:
      - vectorian>=0.8.0.dev12
      - sentence-transformers>=0.4
      - jupyter_bokeh>=3.0.0
      - opentsne>=0.6.0
      - spacy>=3.0.0,<4.0.0
      - spacy_sentence_bert>=0.1.2
      - markdown>=3.3.4
      - networkx>=2.5.1
      - jp_proxy_widget
