name: vectorian-demo
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8
  - bokeh>=2.3.1
  - ipywidgets
  - faiss
  - pip
  - pip:
      - vectorian>=0.8.0.dev11
      - sentence-transformers>=0.4
      - jupyter_bokeh>=3.0.0
      - opentsne>=0.6.0
      - spacy>=3.0.0,<4.0.0
      - spacy_sentence_bert>=0.1.2
      - https://github.com/MartinoMensio/spacy-sentence-bert/releases/download/v0.1.2/en_paraphrase_distilroberta_base_v1-0.1.2.tar.gz#en_paraphrase_distilroberta_base_v1-0.1.2
      - markdown>=3.3.4
